// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: storage.proto

package storagepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CarStock_ListCars_FullMethodName = "/storage.v1.CarStock/ListCars"
	CarStock_GetCar_FullMethodName   = "/storage.v1.CarStock/GetCar"
)

// CarStockClient is the client API for CarStock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CarStock exposes the cars currently available for sale in StorageService.
type CarStockClient interface {
	// ListCars returns every car available in stock.
	ListCars(ctx context.Context, in *ListCarsRequest, opts ...grpc.CallOption) (*ListCarsResponse, error)
	// GetCar returns a single available car by its identifier.
	GetCar(ctx context.Context, in *GetCarRequest, opts ...grpc.CallOption) (*Car, error)
}

type carStockClient struct {
	cc grpc.ClientConnInterface
}

func NewCarStockClient(cc grpc.ClientConnInterface) CarStockClient {
	return &carStockClient{cc}
}

func (c *carStockClient) ListCars(ctx context.Context, in *ListCarsRequest, opts ...grpc.CallOption) (*ListCarsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCarsResponse)
	err := c.cc.Invoke(ctx, CarStock_ListCars_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carStockClient) GetCar(ctx context.Context, in *GetCarRequest, opts ...grpc.CallOption) (*Car, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Car)
	err := c.cc.Invoke(ctx, CarStock_GetCar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarStockServer is the server API for CarStock service.
// All implementations must embed UnimplementedCarStockServer
// for forward compatibility.
//
// CarStock exposes the cars currently available for sale in StorageService.
type CarStockServer interface {
	// ListCars returns every car available in stock.
	ListCars(context.Context, *ListCarsRequest) (*ListCarsResponse, error)
	// GetCar returns a single available car by its identifier.
	GetCar(context.Context, *GetCarRequest) (*Car, error)
	mustEmbedUnimplementedCarStockServer()
}

// UnimplementedCarStockServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCarStockServer struct{}

func (UnimplementedCarStockServer) ListCars(context.Context, *ListCarsRequest) (*ListCarsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCars not implemented")
}
func (UnimplementedCarStockServer) GetCar(context.Context, *GetCarRequest) (*Car, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCar not implemented")
}
func (UnimplementedCarStockServer) mustEmbedUnimplementedCarStockServer() {}
func (UnimplementedCarStockServer) testEmbeddedByValue()                  {}

// UnsafeCarStockServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CarStockServer will
// result in compilation errors.
type UnsafeCarStockServer interface {
	mustEmbedUnimplementedCarStockServer()
}

func RegisterCarStockServer(s grpc.ServiceRegistrar, srv CarStockServer) {
	// If the following call panics, it indicates UnimplementedCarStockServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CarStock_ServiceDesc, srv)
}

func _CarStock_ListCars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCarsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarStockServer).ListCars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CarStock_ListCars_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarStockServer).ListCars(ctx, req.(*ListCarsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarStock_GetCar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarStockServer).GetCar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CarStock_GetCar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarStockServer).GetCar(ctx, req.(*GetCarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CarStock_ServiceDesc is the grpc.ServiceDesc for CarStock service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CarStock_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.v1.CarStock",
	HandlerType: (*CarStockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCars",
			Handler:    _CarStock_ListCars_Handler,
		},
		{
			MethodName: "GetCar",
			Handler:    _CarStock_GetCar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}
